AppMode: debug               # 开发模式, debug, release, test
AppReadTimeout: 120
AppWriteTimeout : 120
AppPort: 6008                  # HTTP绑定端口
AppTitle: 注册中心
AppHost: 127.0.0.1
AppName: registerCenter              # API Server的名字
url: http://127.0.0.1:7001   # pingServer函数请求的API服务器的ip:port
ErrReport : false
SystemId : 1
max_ping_count: 100
img_url: